#!/bin/sh

TIMEOUT_S="5"
LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

while [ true ]; do
    # exit 1 if script itself fails

    # Check if servald is running
    if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
        echo "Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    if [ "$LATER" -lt `date +%s` ]; then
        # echo "Timeout on $HOSTNAME" >&2
        # exit 3
        
        # exit 0 is fine here, for debug purposes
        exit 0
    fi

    sleep 1
done
