#!/bin/sh

#TIMEOUT_S="10"
#LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

while [ true ]; do
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if servald is running
    if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
        echo "ERROR: Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    #if [ "$LATER" -lt `date +%s` ]; then
        # echo "ERROR: Timeout on $HOSTNAME" >&2
        # exit 3
        
        # exit 0 is fine here, for debug purposes
    #    echo "Serval finished on $HOSTNAME" >&2
    #    exit 0
    #fi

    sleep 15
done
