#! /bin/sh
if [ "$1" = "-h" ]; then
    echo "usage: $0 [...]"
    echo "daemonizes a command on every core node"
fi

for f in `find /tmp/  2>/dev/null | grep pycore.*/n[0-9]*$`
do
	echo '# HOST:' ${f##*/}
	vcmd -c $f -- sh -c "nohup $(echo $@) & sleep 1"
    echo
done
