#!/bin/sh
if [ -z $SCRIPT_PATH ]; then SCRIPT_PATH=$(dirname $0); fi
. $SCRIPT_PATH/serval-vars

usage() {
    echo "usage: $0"
    echo "collects and writes SIDs from all CORE serval peers to $SEVERAL_ALL_SIDS_FILE"
}

if [ "$1" = "-h" ]; then usage; exit 0; fi
    
rm -f $SEVERAL_ALL_SIDS_FILE

for f in `find /tmp/  2>/dev/null | grep pycore.*/n[0-9]*$`; do
	vcmd -c $f -- servald id self | egrep [A-F0-9]+{64} | tee -a $SEVERAL_ALL_SIDS_FILE
done

echo "Done."
