#!/bin/bash

print_scenario () {
    scenario=$(ps aux | grep "scenario miniworld" | grep -v grep | awk '{print $(NF)}' | tail -n1)
    if [ -z $scenario ]; then
    	printf "\033[96mCurrent scenario: \033[91mnone\033[m\n"
    else
    	printf "\033[96mCurrent scenario: \033[92m$(basename $scenario)\033[m\n"
    fi
}

if [ "$1" == "-l" ]; then
    clear
    while true; do
    	printf "\033[A\r"
        print_scenario
    	sleep 5
    done
fi

print_scenario
