#!/bin/bash

if [ -z $1 ]; then
  echo "Usage: $0 <directory to tidy up>"
fi

for i in $( find $1 -type d | grep qemu ); do
  mv $i $(python tidy_filename.py $i)
done
for i in $( find $1 -type f | grep qemu ); do
  mv $i $(python tidy_filename.py $i)
done
#find $1 -type f | grep qemu | xargs -L 1 -I FULLNAME mv FULLNAME $(python tidy_filename.py FULLNAME)
