#!/bin/sh

HOSTNAME=`hostname`
TESTFILE_PATH="/tmp/serval-testfiles"
mkdir -p $TESTFILE_PATH
rm -rf $TESTFILE_PATH/*

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"

FILESET="$3"
NUM="$4"

# generate_files <NUM> <PATH> <BYTESIZE> <BYTECOUNT>
generate_files() {
  for cnt in `/usr/bin/seq 1 $1`; do
    /bin/dd if=/dev/urandom of=$2-$cnt.file bs=$3 count=$4
  done
}

generate_small() {
  generate_files $1 "$2/64k" "1K" "64"
  generate_files $1 "$2/256k" "1K" "256"
  generate_files $1 "$2/512k" "1K" "512"
}
generate_medium() {
  generate_files $1 "$2/1m" "1M" "1"
  generate_files $1 "$2/5m" "1M" "5"
  generate_files $1 "$2/10m" "1M" "10"
}
generate_large() {
  generate_files $1 "$2/25m" "1M" "25"
  generate_files $1 "$2/50m" "1M" "50"
  generate_files $1 "$2/100m" "1M" "100"
}


if [ -z $NUM ]; then
  NUM_FILES=1
else
  NUM_FILES=$NUM
fi
echo "Generating $NUM_FILES per type.."
if [ -z $FILESET ]; then
  echo "Default set"
  echo "Generating files on $HOSTNAME: "
  generate_files $NUM_FILES "$TESTFILE_PATH/64k" "1K" "64"
  generate_files $NUM_FILES "$TESTFILE_PATH/256k" "1K" "256"
  generate_files $NUM_FILES "$TESTFILE_PATH/512k" "1K" "512"
elif [ "$FILESET" = "f1" ]; then
  echo "File-Set: f1 - small"
  echo "Generating files on $HOSTNAME: "
  generate_small $NUM_FILES $TESTFILE_PATH
elif [ "$FILESET" = "f2" ]; then
  echo "File-Set: f2 - medium"
  echo "Generating files on $HOSTNAME: "
  generate_medium $NUM_FILES $TESTFILE_PATH
elif [ "$FILESET" = "f3" ]; then
  echo "File-Set: f3 - large"
  echo "Generating files on $HOSTNAME: "
  generate_large $NUM_FILES $TESTFILE_PATH
elif [ "$FILESET" = "f4" ]; then
  echo "File-Set: f4 - combined"
  echo "Generating files on $HOSTNAME: "
  generate_small $NUM_FILES $TESTFILE_PATH
  generate_medium $NUM_FILES $TESTFILE_PATH
  generate_large $NUM_FILES $TESTFILE_PATH
fi
