#!/bin/sh

#TIMEOUT_S="500"
#LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
FILESET="$3"
NUM=$4

if [ -z $NUM ]; then
  echo "The parameters do not match."
  exit 1
fi

if [[ $FILESET = f4 ]]; then
	NUM_FILES=9
else
	NUM_FILES=3
fi

NUM_TO_WAIT=$(( NUM_FILES * TOTAL_ACTIVE_NODES * NUM ))

while [ true ]; do
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if servald is running
    if [ $(servald status | grep stopped | wc -l) -eq 1 ]; then
        echo "ERROR: Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    #if [ "$LATER" -lt `date +%s` ]; then
    #    echo "ERROR: Timeout on $HOSTNAME" >&2
    #    exit 3
    #fi

    # Check if condition is reached
    if [ $(/serval-tests/rhizome-list-bundles-curl | /serval-tests/jsawk | grep '\["rows",[0-9]*\]' | grep -v 'MeshMS2' | wc -l) -eq $NUM_TO_WAIT ]; then
        echo "All files arrived on $HOSTNAME."
	exit 0
    fi

    sleep 15
done
