#!/bin/sh

#TIMEOUT_S="500"
#LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
NUM="$3"

if [ -z $NUM ]; then
  echo "Please provide number of expected files!"
  exit 1
fi

while [ true ]; do
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if servald is running
    if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
        echo "ERROR: Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    #if [ "$LATER" -lt `date +%s` ]; then
    #    echo "ERROR: Timeout on $HOSTNAME" >&2
    #    exit 3
    #fi

    # Check if condition is reached
    if [ $(servald rhizome list | grep ":file:" | wc -l) -eq $NUM ]; then
        exit 0
    fi

    sleep 1
done
