#!/bin/bash

TOTAL_NODES="$1"
TOTAL_NODES_ACTIVE="$2"

TEST_SET="$3"
TIME_VAL="$4"
SALT="$5"

LATER=$((`date +%s` + $TIME_VAL))
SEED=$(( `hostname | tr -dc '0-9'` + $SALT))
RANDOM=$SEED

while [ $LATER -gt `date +%s` ]; do
	rm -rf /root/tmp/serval-testfiles
	$(dirname $0)/prepare-ad-hoc $TOTAL_NODES $TOTAL_NODES_ACTIVE $TEST_SET $(( ( $RANDOM % 10 )  + 1 ))
	
	$(dirname $0)/initiate-mif $TOTAL_NODES $TOTAL_NODES_ACTIVE
	$(dirname $0)/initiate-mim $TOTAL_NODES $TOTAL_NODES_ACTIVE $(( ( $RANDOM % 10 )  + 1 ))
	
	sleep $(( ( ( $RANDOM % $TIME_VAL )  + `hostname | tr -dc '0-9'` ) ))
done
