#!/bin/sh

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
COUNT_OR_TIME="$3"
COUNT_OR_TIME_VAL="$4"
TEST_SET="$5"

if [ "$COUNT_OR_TIME" = "f" ]; then
	if [ "$TEST_SET" = "f1" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 256 -f $COUNT_OR_TIME_VAL`
	elif [ "$TEST_SET" = "f2" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 5000 -f $COUNT_OR_TIME_VAL`
	elif [ "$TEST_SET" = "f3" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 50000 -f $COUNT_OR_TIME_VAL`
	fi
elif [ "$COUNT_OR_TIME" = "t" ]; then
	if [ "$TEST_SET" = "f1" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 256 -t $COUNT_OR_TIME_VAL`
	elif [ "$TEST_SET" = "f2" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 5000 -t $COUNT_OR_TIME_VAL`
	elif [ "$TEST_SET" = "f3" ]; then
		`python /home/meshadmin/serval-tests/SimpleRhizomeAdder.py -s 50000 -t $COUNT_OR_TIME_VAL`
	fi
fi
