#!/bin/sh

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"

TIME_DM="t"
TIME_VAL_DM="$3"

TIME_DDF="t"
TIME_VAL_DDF="$3"
TEST_SET_DDF="$4"

TEST_SET_DF="$4"
COUNT_OR_TIME_DF="$5"
COUNT_OR_TIME_VAL_DF="$6"

TESTFILE_PATH_MIF="$7"

NUM_MSGS_MIM="$8"

echo "Initiating delayed messages..."
/bin/sh initiate-delayed-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DM $TIME_DM_VAL

echo "Initiating delayed direct files..."
/bin/sh initiate-delayed-direct-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DDF $TIME_VAL_DDF $TEST_SET_DDF

echo "Initiating delayed files..."
/bin/sh initiate-delayed-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $TEST_SET_DF $COUNT_OR_TIME_DF $COUNT_OR_TIME_VAL_DF

echo "Initiating mass inject files..."
/bin/sh initiate-mass-inject-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $TESTFILE_PATH_MIF

echo "Initiating mass inject messages..."
/bin/sh initiate-mass-inject-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $NUM_MSGS_MIM
