#!/bin/sh

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"

TIME_DM="t"
TIME_VAL_DM="$3"

TIME_DDF="t"
TIME_VAL_DDF="$3"

COUNT_OR_TIME_DF="$4"
COUNT_OR_TIME_VAL_DF="$5"

NUM_MIF="$6"

NUM_MSGS_MIM="$7"

echo "Initiating delayed messages..."
/bin/sh watch-agent-delayed-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DM $TIME_DM_VAL

echo "Initiating delayed direct files..."
/bin/sh watch-agent-delayed-direct-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $TIME_DDF $TIME_VAL_DDF

echo "Initiating delayed files..."
/bin/sh watch-agent-delayed-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $COUNT_OR_TIME_DF $COUNT_OR_TIME_VAL_DF

echo "Initiating mass inject files..."
/bin/sh watch-agent-mass-inject-files $TOTAL_NODES $TOTAL_ACTIVE_NODES $NUM_MIF

echo "Initiating mass inject messages..."
/bin/sh watch-agent-mass-inject-messages $TOTAL_NODES $TOTAL_ACTIVE_NODES $NUM_MSGS_MIM
