#!/bin/sh

#TIMEOUT_S="120"
#LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`
SID=$(servald id self | tail -n 1)

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
NUM_MSGS="$3"

case $NUM_MSGS in
    '' | *[!0-9]*)
        NUMBER_OF_MESSAGES=5;;
    *)
        NUMBER_OF_MESSAGES=$NUM_MSGS;;
esac

# Check if node is the active node in a setpu with more than two nodes 
if [ -f /tmp/$HOSTNAME.active ]; then
	exit 0
fi

while [ true ]; do
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if servald is running
    if [ $(servald status | grep stopped | wc -l) -eq 1 ]; then
        echo "ERROR: Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    #if [ "$LATER" -lt `date +%s` ]; then
    #    echo "ERROR: Timeout on $HOSTNAME" >&2
    #    exit 3
    #fi

    # Check if node received the messages from the active node
    CONV_LIST=$(/serval-tests/meshms-list-conv-curl $SID)
    if [ $(echo $CONV_LIST | /serval-tests/jsawk | grep '\["rows",[0-9]*\]' | wc -l) -gt 0 ]; then
        # Get SID of active node
        SENDER=$(echo $CONV_LIST | /serval-tests/jsawk | grep '\["rows",[0-9]*\]' | tail -n 1 | awk '{split($0,a,","); print a[4]}' | tr -d '"')
        if [ -z ${SENDER} ]; then
            continue
        fi
        if [ $(/serval-tests/meshms-list-mess-curl $SID $SENDER | /serval-tests/jsawk | grep '\["rows",[0-9]*\]' | wc -l) -ge $NUMBER_OF_MESSAGES ]; then
        # Check if node received the specified number of messages from the active node
            ## -eq SHOULD be perfectly fine in this if, in some cases messages are sent multiple times.
            echo "$HOSTNAME finished"
            exit 0
        fi
    fi
    sleep 15
done
