#!/bin/sh

TIMEOUT_S="120"
LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`
SID=$(servald id self | tail -n 1)
NUMBER_OF_HEADER_LINES=2

case $2 in
    '' | *[!0-9]*)
        NUMBER_OF_MESSAGES=5;;
    *)
        NUMBER_OF_MESSAGES=$2;;
esac

while [ true ]; do
    # Check if servald is running
    if [ $(ps aux | grep "servald start" | grep -v grep | wc -l) -lt 1 ]; then
        echo "Serval crashed on $HOSTNAME" >&2
        exit 1
    fi

    # Check if test timed out
    if [ "$LATER" -lt `date +%s` ]; then
        echo "Timeout on $HOSTNAME" >&2
        exit 2
    fi

    # Check if node received the messages from the active node
    if [ $(servald meshms list conversations $SID | wc -l) -eq 3 ]; then
        # Get SID of active node
        SENDER=$( servald meshms list conversations $SID | tail -n 1 | awk '{split($0,a,":"); print a[2]}')
        # Check if node received the specified number of messages from the active node
        if [ $(servald meshms list messages $SID $SENDER | wc -l) -eq $(( $NUMBER_OF_HEADER_LINES+$NUMBER_OF_MESSAGES )) ]; then
            echo "$HOSTNAME finished"
            exit 0
        fi
    # Check if node is 
    elif [ $(servald meshms list conversations $SID | wc -l) -gt 3 ]; then
        exit 0
    fi

    sleep 1
done
