#!/bin/sh

#TIMEOUT_S="120"
#LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`
SID=$(servald id self | tail -n 1)
NUMBER_OF_HEADER_LINES=2

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
NUM_MSGS="$3"

case $NUM_MSGS in
    '' | *[!0-9]*)
        NUMBER_OF_MESSAGES=5;;
    *)
        NUMBER_OF_MESSAGES=$NUM_MSGS;;
esac

while [ true ]; do
    sleep 1
    # returns 1 if script itself fails
    # returns 255 if ssh/vcmd session fails

    # Check if servald is running
    if [ `(ps aux 2> /dev/null || ps w) | grep "servald start" | grep -v grep | wc -l` -lt 1 ]; then
        echo "ERROR: Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    #if [ "$LATER" -lt `date +%s` ]; then
    #    echo "ERROR: Timeout on $HOSTNAME" >&2
    #    exit 3
    #fi

    # Check if node received the messages from the active node
    if [ $(servald meshms list conversations $SID | wc -l) -eq 3 ]; then
        # Get SID of active node
        SENDER=$( servald meshms list conversations $SID | tail -n 1 | awk '{split($0,a,":"); print a[2]}')
        if [ -z ${SENDER} ]; then
            continue
        fi
        # Check if node received the specified number of messages from the active node
        if [ $(servald meshms list messages $SID $SENDER | wc -l) -ge $(( $NUMBER_OF_HEADER_LINES+$NUMBER_OF_MESSAGES )) ]; then
            ## -eq SHOULD be perfectly fine in this if, in some cases messages are sent multiple times.
            echo "$HOSTNAME finished"
            exit 0
        fi
    # Check if node is the active node in a setpu with more than two nodes 
    elif [ $(servald meshms list conversations $SID | wc -l) -gt 3 ]; then
        exit 0
    fi

done
