#!/bin/sh

TIMEOUT_S="500"
LATER=$((`date +%s` + $TIMEOUT_S))
HOSTNAME=`hostname`

TOTAL_NODES="$1"
TOTAL_ACTIVE_NODES="$2"
COUNT_OR_TIME="$3"
COUNT_OR_TIME_VAL="$4"

TOTAL_FILES=$(($COUNT_OR_TIME_VAL * $TOTAL_ACTIVE_NODES))

if [ "$COUNT_OR_TIME" = "t" ]; then
	SCENARIO_TIMEOUT="$COUNT_OR_TIME_VAL"
	SCENARIO_LATER=$((`date +%s` + $SCENARIO_TIMEOUT))
fi

while [ true ]; do
    # exit 1 if script itself fails

    # Check if servald is running
    if [ $(ps aux | grep "servald start" | grep -v grep | wc -l) -lt 1 ]; then
        echo "Serval crashed on $HOSTNAME" >&2
        exit 2
    fi

    # Check if test timed out
    if [ "$LATER" -lt `date +%s` ]; then
        echo "Timeout on $HOSTNAME" >&2
        exit 3
    fi

    # Check if condition is reached
    if [ "$COUNT_OR_TIME" = "f" ]; then
    	if [ $(servald rhizome list | grep ":file:" | wc -l) -eq $TOTAL_FILES ]; then
    		echo "All file arrived on $HOSTNAME"
    		exit 0
    	fi
    elif [ "$COUNT_OR_TIME" = "t" ]; then
    	if [ "$SCENARIO_LATER" -lt `date +%s` ]; then
    		echo "Timout reached on $HOSTNAME"
    		exit 0
    	fi
    fi

    sleep 1
done
